// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/activity-logs" | "/admin/analysis" | "/admin/broadcast" | "/admin/change-password" | "/admin/login" | "/admin/qr" | "/admin/reward-exchanges" | "/admin/user-logs"
type AppRouteHandlerRoutes = "/api/activity-logs" | "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/signup" | "/api/broadcast/logs" | "/api/broadcast/preview" | "/api/broadcast/send" | "/api/event-logs" | "/api/families" | "/api/families/[family_id]" | "/api/families/[family_id]/members" | "/api/families/[family_id]/members/[user_id]" | "/api/profiles" | "/api/profiles/[id]" | "/api/profiles/[id]/care-messages" | "/api/profiles/[id]/stamp" | "/api/profiles/[id]/stamp-set" | "/api/reward-exchanges" | "/api/reward-exchanges/[id]/cancel" | "/api/reward-exchanges/[id]/complete" | "/api/reward-exchanges/[id]/delete" | "/api/users/[userId]/reservation-click"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/activity-logs": {}
  "/admin/analysis": {}
  "/admin/broadcast": {}
  "/admin/change-password": {}
  "/admin/login": {}
  "/admin/qr": {}
  "/admin/reward-exchanges": {}
  "/admin/user-logs": {}
  "/api/activity-logs": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/signup": {}
  "/api/broadcast/logs": {}
  "/api/broadcast/preview": {}
  "/api/broadcast/send": {}
  "/api/event-logs": {}
  "/api/families": {}
  "/api/families/[family_id]": { "family_id": string; }
  "/api/families/[family_id]/members": { "family_id": string; }
  "/api/families/[family_id]/members/[user_id]": { "family_id": string; "user_id": string; }
  "/api/profiles": {}
  "/api/profiles/[id]": { "id": string; }
  "/api/profiles/[id]/care-messages": { "id": string; }
  "/api/profiles/[id]/stamp": { "id": string; }
  "/api/profiles/[id]/stamp-set": { "id": string; }
  "/api/reward-exchanges": {}
  "/api/reward-exchanges/[id]/cancel": { "id": string; }
  "/api/reward-exchanges/[id]/complete": { "id": string; }
  "/api/reward-exchanges/[id]/delete": { "id": string; }
  "/api/users/[userId]/reservation-click": { "userId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
