// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/activity-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/activity-logs">> = Specific
  const handler = {} as typeof import("../../app/admin/activity-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analysis">> = Specific
  const handler = {} as typeof import("../../app/admin/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/broadcast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/broadcast">> = Specific
  const handler = {} as typeof import("../../app/admin/broadcast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/change-password">> = Specific
  const handler = {} as typeof import("../../app/admin/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qr">> = Specific
  const handler = {} as typeof import("../../app/admin/qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reward-exchanges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reward-exchanges">> = Specific
  const handler = {} as typeof import("../../app/admin/reward-exchanges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/user-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/user-logs">> = Specific
  const handler = {} as typeof import("../../app/admin/user-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/activity-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity-logs">> = Specific
  const handler = {} as typeof import("../../app/api/activity-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/broadcast/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/broadcast/logs">> = Specific
  const handler = {} as typeof import("../../app/api/broadcast/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/broadcast/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/broadcast/preview">> = Specific
  const handler = {} as typeof import("../../app/api/broadcast/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/broadcast/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/broadcast/send">> = Specific
  const handler = {} as typeof import("../../app/api/broadcast/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/event-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/event-logs">> = Specific
  const handler = {} as typeof import("../../app/api/event-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[family_id]/members/[user_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[family_id]/members/[user_id]">> = Specific
  const handler = {} as typeof import("../../app/api/families/[family_id]/members/[user_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[family_id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[family_id]/members">> = Specific
  const handler = {} as typeof import("../../app/api/families/[family_id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[family_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[family_id]">> = Specific
  const handler = {} as typeof import("../../app/api/families/[family_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families">> = Specific
  const handler = {} as typeof import("../../app/api/families/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profiles/[id]/care-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/[id]/care-messages">> = Specific
  const handler = {} as typeof import("../../app/api/profiles/[id]/care-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profiles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/profiles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profiles/[id]/stamp-set/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/[id]/stamp-set">> = Specific
  const handler = {} as typeof import("../../app/api/profiles/[id]/stamp-set/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profiles/[id]/stamp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/[id]/stamp">> = Specific
  const handler = {} as typeof import("../../app/api/profiles/[id]/stamp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reward-exchanges/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reward-exchanges/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/reward-exchanges/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reward-exchanges/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reward-exchanges/[id]/complete">> = Specific
  const handler = {} as typeof import("../../app/api/reward-exchanges/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reward-exchanges/[id]/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reward-exchanges/[id]/delete">> = Specific
  const handler = {} as typeof import("../../app/api/reward-exchanges/[id]/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reward-exchanges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reward-exchanges">> = Specific
  const handler = {} as typeof import("../../app/api/reward-exchanges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[userId]/reservation-click/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[userId]/reservation-click">> = Specific
  const handler = {} as typeof import("../../app/api/users/[userId]/reservation-click/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
